version: '3'
services:

  web:
    depends_on:
      - postgres
    build: .
    container_name: web
    ports:
      - "5001:5001"

  postgres:
    image: postgres
    container_name: mytemplatedb
    environment:
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_USER=test_db_user
    ports:
      - "54320:5432"





